name: Generate PDF

on: ["deployment"]

jobs:
  generate:
    name: Generate PDF
    runs-on: ubuntu-latest
    steps:
      - name: html to pdf
        uses: misaelnieto/web_to_pdf_action@v0.3.1
        with:
          webPageURL: https://siredmar.github.io/online-cv/
          outputFile: ./assets/pdf/Resume.pdf
          usePuppeteer: true
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
